name: demo_mlflow_ret
channels:
  - defaults
dependencies:
  - python=3.10.8
  - numpy>=1.14.3
  - pandas>=1.0.0
  - scikit-learn>0.19.1
  - pip
  - pip:
    - mlflow
    - python-dotenv
    - boto3
    - s3fs